autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': false
  bcrypt: set this to true or false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: false
